version: '3.8'

services:
  # SQL Server
  sqlserver:
    container_name: venice-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=VeniceOrders@2024
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - venice_network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P VeniceOrders@2024 -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 180s

  # MongoDB
  mongodb:
    container_name: venice-mongodb
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - venice_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s

  # Redis
  redis:
    container_name: venice-redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - venice_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  # RabbitMQ
  rabbitmq:
    container_name: venice-rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=venice_user
      - RABBITMQ_DEFAULT_PASS=VeniceMQ2024
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - venice_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s

  # Venice Orders API
  venice-orders-api:
    container_name: venice-orders-api
    build:
      context: ./src
      dockerfile: Venice.Orders.WebApi/Dockerfile
    ports:
      - "5050:80"   # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORT=80
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=false
    depends_on:
      - sqlserver
      - mongodb
      - redis
      - rabbitmq
    networks:
      - venice_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  sqlserver_data:
  mongodb_data:
  rabbitmq_data:

networks:
  venice_network:
    driver: bridge




